let wordlistLanguage = 'english';

let expectedPublicKeys = [
  // these are the two FullAccess keys on the puzzlemaster.near
  // account as at block hash AUuoUf2hZBWoxGF7bDuPzuyM88NHSEEr63sKgUQoHMLz
  // --
  'ed25519:43oLtgANKwkXnyEGuCb1McGZoAydJQ56ykXcx6wDnCnK',
  'ed25519:BTyLuYU4GzZEEN6wDPv3m1p14wLxhwnNFcymqrzNZrib',
];

let guesses = [
  [
    // DAY 1
    'drink',
    'glass',
    'zero',
    'sugar',
    'plastic',
    'soda',
    'alcohol',
    'airport',
    'bubble',
    // - 'bottle',
    // - 'beverage',
    // - 'beer',
    // - 'passenger',
    // - 'coat',
  ],
  [
    // DAY 2
    'basket',
    'bread',
    'cream',
    'paper',
    'plate',
    'net',
    'table',
    'food',
    'metal',
    'iron',
    'desk',
    // - 'pie',
    // - 'pastry',
    // - 'bowl',
    // - 'eating',
    // - 'ceramic',
    // - 'white',
    // - 'tasty',
    // - 'delicious',
  ],
  [
    // DAY 3
    'salon',
    'open',
    'hair',
    'beauty',
    'hundred',
    'black',
    'gold',
    'social',
    'number',
    'front',
    'small',
    'circle',
    'salon',
    'glass',
    'blur',
    'grass',
    'tree',
    'leaf',
    'open',
    // - 'big',
    // - 'entrance',
    // - 'barber',
    // - 'leaves',
    // - 'kiosk'
  ],
  [
    // DAY 4
    'mountain',
    'snow',
    'cloud',
    'high',
    'below',
    'top',
    'blue',
    'height',
    'tiny',
    'mirror',
    'sunset',
    // - 'horizon',
    // - 'landscape',
    // - 'line',
    // - 'sky',
    // - 'summit',
    // - 'peak',
    // - 'flying',
    // - 'up',
  ],
  [
    // DAY 5
    'sand',
    'beach',
    'hold',
    'crisp',
    'snack',
    'wave',
    'sea',
    'finger',
    'hand',
    'onion',
    'cheese',
    // - 'chip',
    // - 'pringle',
    // - 'crack',
    // - 'walker',
    // - 'sky',
  ],
  [
    // DAY 6
    'beyond',
    'six',
    'eight',
    // - 'hexadecimal',
    // - 'white',
  ],
  [
    // DAY 7
    'fragile',
    'empty',
    'entry',
    'guard',
    // - 'string',
    // - 'envy',
    // - 'sent',
    // - 'gibberish',
    // - 'tyre'
  ],
  [
    // DAY 8
    'project',
    'near',
    'ask',
    'auction',
    'three',
    'moon',
    'market',
    'art',
    'artwork',
    // - 'blockchain',
    // - 'hype'
  ],
  [
    // DAY 9
    'attack',
    'energy',
    'fire',
    'mule',
    'game',
    'fun',
    // - 'attribute',
    // - 'axe',
    // - 'strength',
    // - 'dexterity',
    // - 'vitality',
    // - 'player',
    // - 'character',
  ],
  [
    // DAY 10
    'grass',
    'whip',
    'trim',
    'man',
    'blur',
    // - 'cut',
    // - 'weed',
    // - 'red',
    // - 'leaves',
  ],
  [
    // DAY 11
    'trophy',
    'gold',
    'victory',
    'medal',
    'icon',
    // - 'period',
  ],
  [
    // DAY 12
    'secret',
    'skeleton',
    'token',
    'build',
    'hat',
    'green',
  ],
];

module.exports = {
  guesses,
  wordlistLanguage,
  expectedPublicKeys,
};
